# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wh4YGFBnEleWhtaYAPUF98pQXo2RLks6

For the given 'Iris' dataset, create the Decision Tree classifier and visualize it graphically. The purpose is if we feed any new data to this classfier , it woulld be able to predict the right class accordingly.
"""

from sklearn.tree import DecisionTreeClassifier
import sklearn.datasets as datasets
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
import pandas as pd


iris=datasets.load_iris()
iris_df=pd.DataFrame(iris.data, columns=iris.feature_names)
print(iris_df.head(5))

u=iris.target
print(u)

"""Defining Decision Tree"""

dtree=DecisionTreeClassifier()
dtree.fit(iris_df,u)

"""Visualizing Graph"""

dot_data = StringIO()
export_graphviz(dtree, out_file=dot_data, feature_names=iris.feature_names,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())